name: "Docker Action Example"
description: "A simple action docker based"
inputs:
  name:
    description: "Username"
    required: true
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--name=${{ inputs.name }}"
