name: 'My Composite Action'
description: 'A Composite Action to show how works'
inputs:
  name:
    description: 'Username'
    required: true
outputs:
  result:
    description: 'Final message'
    value: ${{ steps.final-message.outputs.message }}
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Execute script
      id: run-script
      shell: bash
      run: |
        echo "Hello, ${{ inputs.name }}! This is a script inside of a composite action."
        chmod +x ${{ github.action_path }}/script.sh
        ${{ github.action_path }}/script.sh ${{ inputs.name }}

    - name: Final message
      id: final-message
      shell: bash
      run: |
        echo "Everything is ok, ${{ inputs.name }}!" 
        echo "message=Command executed successfully!" >> $GITHUB_OUTPUT
