name: "JavaScript Action Example"
description: "An Javascript action"
inputs:
  name:
    description: "Username"
    required: true
    default: "World"
outputs:
  greeting:
    description: "Greeting message"
runs:
  using: "node20" # Usa Node.js 20
  main: "index.js" # Arquivo principal da action
