apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secrets
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
  API_KEY: c2VjcmV0a2V5MTIz      # base64 encoded "secretkey123" 