name: 01 - Linux Commands Example Workflow

on:
  workflow_dispatch:

jobs:
  run_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Print Operating System Info
        run: |
          echo "This command prints info about the s.o."
          uname -a
          
      - name: List Files in Current Directory
        run: |
          echo "This command list Files in Current Directory."
          ls -l
          
      - name: Print Current Working Directory
        run: |
          echo "Print Current Working Directory."
          pwd
          
      - name: Print Environment Variables
        run: |
          echo "Print Environment Variables."
          printenv
