name: Print a text
on:
  workflow_call:
    inputs:
      input_text:
        required: true
        type: string

jobs:
  show-input-text:
    runs-on: ubuntu-latest

    steps:      

      - name: Print text
        id: print-text
        run: |
        echo "text provide was: $input_text" >> $GITHUB_ENV