name: "02.1 - Main Workflow Using Reusable Workflow"
on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    name: "Call Reusable Workflow"
    uses: ./.github/workflows/_reusable-workflow.yaml
    with:
      MESSAGE: "Hello from the Main Workflow! 🚀"
      RUNNER: "ubuntu-latest"
