name: 03 - Execute Docker and mount GitHub Workspace

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v3

      - name: Generate file
        run: echo "This is a file test generate during CI execution" > testfile.txt

      - name: Run Docker container
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" alpine /bin/sh -c "
            echo 'Inside of Docker container';
            pwd;
            ls -la /workspace;
          "
