name: Print a text workflow

on:
  workflow_dispatch:

jobs:
  print-text:
    uses: rmnobarra/github-actions-playground/.github/workflows/02-reusable-workflow.yaml@main
    with:
      input-text: "Hello there"

  print-some-text-and-send-to-env:
    runs-on: ubuntu-latest
    name: Print some text and send to env job
    outputs:
      hash_value: ${{ steps.set_hash.outputs.hash_output }}
    steps:
      - name: Print some text and send to env step
        id: set_hash
        run: echo "hash_output=$(head -c 12 /dev/urandom | base64)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Print some text and send to env step inside the same job
        run: echo $hash_output
        shell: bash

  print-some-text-outside-of-the-job:
    runs-on: ubuntu-latest
    needs: print-some-text-and-send-to-env
    name: Print some text outside of the job
    steps:
      - name: Print HASH value from previous job
        run: echo "The HASH value is ${{ needs.print-some-text-and-send-to-env.outputs.hash_value }}"
        shell: bash