name: "03 - Main Workflow Using Reusable Workflow"
on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    name: "Call Reusable Workflow"
    uses: ./.github/workflows/reusable-workflow.yaml  # Referência ao reusable workflow
    with:
      MESSAGE: "Hello from the Main Workflow! 🚀"
      RUNNER: "ubuntu-latest"
