name: Print a text

on:
  workflow_dispatch:

jobs:
  print-a-text:
    runs-on: ubuntu-latest
    name: Print a text
    steps:
      - name: Call Reusable Workflow
        uses: rmnobarra/github-actions-playground/.github/workflows/02-reusable-workflow.yaml@main
        with:
          input_text: "Hello, World!"
