name: 04 - Uses Docker Mount Workspace Action

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate file
        run: echo "This is a file test generate during CI execution" > testfile.txt

      - name: Use Docker Mount Workspace Action
        uses: ./actions/run-docker-container-with-volume
        with:
          PATH_TO_MOUNT: ${{ github.workspace }}