name: Usar Docker Mount Workspace Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Docker Mount Workspace Action
        uses: rmnobarra/github-actions-playground@main
        with:
          PATH_TO_MOUNT: ${{ github.workspace }}