name: "07 - Simple Matrix Example"

on: [push]

jobs:
  deploy:
    name: Deploy in ${{ matrix.environment }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [development, staging, production]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shows environment 
        run: |
          echo "Environment Deployment: ${{ matrix.environment }}"


      - name: Execute deployment script
        run: |
          echo "Starts deployment..."
          echo "Environment selected: ${{ matrix.environment }}"
          echo "Deployment successful!"

