name: "07 - Simple Matrix Example"

on: [push]

jobs:
  deploy:
    name: Deploy em ${{ matrix.environment }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [development, staging, production] # Lista de valores

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exibir ambiente
        run: echo "Deploy no ambiente: ${{ matrix.environment }}"

      - name: Executar script de deploy
        run: |
          echo "Iniciando deploy..."
          echo "Ambiente selecionado: ${{ matrix.environment }}"
          echo "Deploy concluído com sucesso!"
