name: "08 - Docker Action Example"

on: [push]

jobs:
  run-docker-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute Docker Action
        uses: ./actions/docker-action
        with:
          name: "GitHub User"

      - name: End of workflow
        run: echo "Workflow completed successfully!"
