name: "09 - JavaScript Action Demo"

on: [push]

jobs:
  run-javascript-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute JavaScript Action
        id: generate-greeting
        uses: ./actions/java-script-action
        with:
          name: "GitHub User"

      - name: Show message
        run: |
          echo "Greeting: ${{ steps.generate-greeting.outputs.greeting }}"
