name: "10 - Secrets and Variables Demo"

on: [push]

jobs:
  demo-secrets-variables:
    name: "Demonstrate Secrets and Variables"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of repository
        uses: actions/checkout@v3

      - name: Show Variable in Repository
        run: |
          echo "The variable is: ${{ vars.MY_VARIABLE }}"

      - name: Show Secret
        run: |
          echo "The secret is: ${{ secrets.MY_SECRET }}"

      - name: Use Secret Securely
        run: |
          echo "The secret should not appear in logs!"
          echo "::add-mask::${{ secrets.MY_SECRET }}"
          echo "Masked Secret: ${{ secrets.MY_SECRET }}"
