name: Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      hotfix:
        description: 'Is this a hotfix deployment?'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Deploy Action
        uses: ./actions/dummy-deploy-action
        with:
          hotfix: ${{ inputs.hotfix }} 